// File generated by the FlutterFire CLI — this is a PLACEHOLDER.
//
// Do NOT ship this file as-is. Run the following from the project root
// once you have created a Firebase project (see README.md, section
// "Firebase Setup"):
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// That command talks to your Firebase project and regenerates this
// file with real, project-specific values for Android, iOS, web,
// macOS, and Windows. It also drops google-services.json and
// GoogleService-Info.plist into the right native folders for you.
//
// The values below are intentionally invalid placeholders so this
// project fails fast and loudly if you forget the step above, instead
// of silently pointing at a Firebase project that isn't yours.

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Run `flutterfire configure` to add support for it.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1bFhsiCSvuUwGJ2Y5gAlezOMk-j8b6qM',
    appId: '1:57278783513:web:0fb5f009b728091b034a88',
    messagingSenderId: '57278783513',
    projectId: 'lideh-live',
    authDomain: 'lideh-live.firebaseapp.com',
    storageBucket: 'lideh-live.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaVT04cXHubljvSyXdvDO38Imt8ujeryA',
    appId: '1:57278783513:android:e747c8531835da04034a88',
    messagingSenderId: '57278783513',
    projectId: 'lideh-live',
    storageBucket: 'lideh-live.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUBStidlwmbW0nnNjd80WJzXcTaFA6NHg',
    appId: '1:57278783513:ios:c326916a5ea16738034a88',
    messagingSenderId: '57278783513',
    projectId: 'lideh-live',
    storageBucket: 'lideh-live.firebasestorage.app',
    iosBundleId: 'com.example.lidehLiveFlutter',
  );
}
